---
  host:
    description: "The IP address or FDQN the Nomad server"
    type: "string"
    secret: false
    required: true
  secure:
    description:
    type: "boolean"
    secret: false
    required: false
    default: false
  token:
    description: "Authentication token"
    type: "string"
    secret: true
    required: false
  verify:
    description: "Whether to verify the SSL certificate or not"
    type: "boolean"
    secret: false
    default: true
  region:
    description: "Nomad region"
    type: "string"
    secret: false